# Generated by Django 3.1.2 on 2021-02-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_numberid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextOz',
        ),
    ]
